name: Análise de Vulnerabilidades com Horusec

on:
  push:
    branches:
      - main # Altere para 'master' se for o caso

jobs:
  horusec-security:
    name: Horusec SAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Essencial para identificar autores

      - name: Rodar Horusec CLI e Gerar JSON
        run: |
          # 1. Baixa o Horusec CLI
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest

          # 2. Executa a análise e salva a saída em JSON
          # '-O ./horusec-report.json' é o que gera o arquivo de dados.
          horusec start -p="./" -o json -O ./horusec-report.json

      - name: Salvar o Relatório JSON
        uses: actions/upload-artifact@v4
        with:
          name: horusec-report-json
          path: horusec-report.json
          retention-days: 1